In [3]:
import numpy as np

In [4]:
print("="*60)
print("1. МОДЕЛИРОВАНИЕ ВХОДНЫХ ДАННЫХ СЛАУ")
print("="*60)
#СЛАУ, которую можно решить методом Холецкого
print("\nа) СЛАУ, которую МОЖНО решить методом Холецкого:")
print("   (симметричная положительно определённая матрица 5×5)")
A_good = np.array([
    [4.0, 1.0, 0.5, 0.2, 0.1],
    [1.0, 5.0, 1.5, 0.3, 0.2],
    [0.5, 1.5, 6.0, 1.0, 0.4],
    [0.2, 0.3, 1.0, 7.0, 1.2],
    [0.1, 0.2, 0.4, 1.2, 8.0]
], dtype=float)
b_good = np.array([1.0, 2.0, 3.0, 4.0, 5.0], dtype=float)
print(f"\nМатрица A (5×5):")
print(A_good)
print(f"\nВектор b:")
print(b_good)
#Теоретическое обоснование:
print("\nТеоретическое обоснование:")
print("- Матрица симметрична: A = A^T")
print("- Положительно определена: все главные миноры > 0")
print("- Собственные значения: все положительные")
print("→ Метод Холецкого применим (A = LL^T, где L - нижняя треугольная)")
#СЛАУ, которую НЕЛЬЗЯ решить методом Холецкого
print("\n\nб) СЛАУ, которую НЕЛЬЗЯ решить методом Холецкого:")
print("   (симметричная, но не положительно определённая матрица 5×5)")
A_bad = np.array([
    [1.0, 2.0, 3.0, 4.0, 5.0],
    [2.0, 4.0, 6.0, 8.0, 10.0],
    [3.0, 6.0, 9.0, 12.0, 15.0],
    [4.0, 8.0, 12.0, 16.0, 20.0],
    [5.0, 10.0, 15.0, 20.0, 25.0]
], dtype=float)
b_bad = np.array([1.0, 2.0, 3.0, 4.0, 5.0], dtype=float)
print(f"\nМатрица A (5×5):")
print(A_bad)
print(f"\nВектор b:")
print(b_bad)
# Теоретическое обоснование:
print("\nТеоретическое обоснование:")
print("- Матрица симметрична: A = A^T")
print("- Но вырождена: определитель = 0")
print("- Не положительно определена: собственные значения не все > 0")
print("→ Метод Холецкого неприменим (при вычислении l_ii получим корень из отрицательного числа или 0)")

1. МОДЕЛИРОВАНИЕ ВХОДНЫХ ДАННЫХ СЛАУ

а) СЛАУ, которую МОЖНО решить методом Холецкого:
   (симметричная положительно определённая матрица 5×5)

Матрица A (5×5):
[[4.  1.  0.5 0.2 0.1]
 [1.  5.  1.5 0.3 0.2]
 [0.5 1.5 6.  1.  0.4]
 [0.2 0.3 1.  7.  1.2]
 [0.1 0.2 0.4 1.2 8. ]]

Вектор b:
[1. 2. 3. 4. 5.]

Теоретическое обоснование:
- Матрица симметрична: A = A^T
- Положительно определена: все главные миноры > 0
- Собственные значения: все положительные
→ Метод Холецкого применим (A = LL^T, где L - нижняя треугольная)


б) СЛАУ, которую НЕЛЬЗЯ решить методом Холецкого:
   (симметричная, но не положительно определённая матрица 5×5)

Матрица A (5×5):
[[ 1.  2.  3.  4.  5.]
 [ 2.  4.  6.  8. 10.]
 [ 3.  6.  9. 12. 15.]
 [ 4.  8. 12. 16. 20.]
 [ 5. 10. 15. 20. 25.]]

Вектор b:
[1. 2. 3. 4. 5.]

Теоретическое обоснование:
- Матрица симметрична: A = A^T
- Но вырождена: определитель = 0
- Не положительно определена: собственные значения не все > 0
→ Метод Холецкого неприменим (при вычислении l_

In [5]:
print("\n" + "="*60)
print("2. РЕАЛИЗАЦИЯ МЕТОДА ХОЛЕЦКОГО")
print("="*60)

def cholesky_decomposition(A):
    n = A.shape[0]
    L = np.zeros((n, n), dtype=float)
    for i in range(n):
        for j in range(i + 1):
            if i == j:
                s = sum(L[i][k] ** 2 for k in range(j))
                diag_val = A[i][i] - s
                if diag_val <= 0:
                    raise ValueError(f"Матрица не положительно определена: l_{i+1}{i+1}² = {diag_val} <= 0")
                L[i][j] = np.sqrt(diag_val)
            else:
                s = sum(L[i][k] * L[j][k] for k in range(j))
                L[i][j] = (A[i][j] - s) / L[j][j]
    return L

def solve_cholesky(A, b):
    #Разложение Холецкого: A = LL^T
    L = cholesky_decomposition(A)
    n = len(b)
    y = np.zeros(n)
    for i in range(n):
        y[i] = (b[i] - sum(L[i][j] * y[j] for j in range(i))) / L[i][i]
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - sum(L[j][i] * x[j] for j in range(i + 1, n))) / L[i][i]
    return x, L


2. РЕАЛИЗАЦИЯ МЕТОДА ХОЛЕЦКОГО
Метод Холецкого реализован:
- Функция cholesky_decomposition(A): выполняет разложение A = LL^T
- Функция solve_cholesky(A, b): решает СЛАУ Ax = b


In [6]:
print("\n" + "="*60)
print("3. РЕШЕНИЕ СЛАУ МЕТОДОМ ХОЛЕЦКОГО")
print("="*60)

#Решение применимой системы
print("\nа) Решение применимой системы:")

try:
    x_solution, L_matrix = solve_cholesky(A_good, b_good)
    print(f"Решение x:")
    print(x_solution)
    residual = np.linalg.norm(A_good @ x_solution - b_good)
    print(f"\nПроверка: ||Ax - b|| = {residual:.2e}")
    A_reconstructed = L_matrix @ L_matrix.T
    reconstruction_error = np.linalg.norm(A_good - A_reconstructed)
    print(f"Проверка разложения: ||A - LL^T|| = {reconstruction_error:.2e}")
except ValueError as e:
    print(f"Ошибка: {e}")

#Попытка решения неприменимой системы
print("\nб) Попытка решения неприменимой системы:")

try:
    x_bad_solution, L_bad = solve_cholesky(A_bad, b_bad)
    print(f"Решение x:")
    print(x_bad_solution)
except ValueError as e:
    print(f"Метод Холецкого не сработал, как и ожидалось:")
    print(f"Ошибка: {e}")


3. РЕШЕНИЕ СЛАУ МЕТОДОМ ХОЛЕЦКОГО

а) Решение применимой системы:
Решение x:
[0.11676352 0.23200409 0.32650192 0.41918561 0.53853742]

Проверка: ||Ax - b|| = 4.44e-16
Проверка разложения: ||A - LL^T|| = 8.89e-16

б) Попытка решения неприменимой системы:
Метод Холецкого не сработал, как и ожидалось:
Ошибка: Матрица не положительно определена: l_22² = 0.0 <= 0


In [7]:
print("\n" + "="*60)
print("4. ОЦЕНКА ЧИСЛА ОПЕРАЦИЙ И СРАВНЕНИЕ С ДРУГИМИ МЕТОДАМИ")
print("="*60)

def estimate_operations(n):
    # Метод Холецкого
    chol_decomp = n**3 / 6 + n**2 / 2 + n/3
    chol_solve = 2 * n**2
    chol_total = chol_decomp + chol_solve
    # Метод Гаусса (LU-разложение)
    gauss_decomp = 2 * n**3 / 3 - n**2 / 2 - n/6
    gauss_solve = 2 * n**2
    gauss_total = gauss_decomp + gauss_solve
    return {
        'Холецкий': {
            'Разложение': chol_decomp,
            'Решение': chol_solve,
            'Всего': chol_total
        },
        'Гаусс': {
            'Разложение': gauss_decomp,
            'Решение': gauss_solve,
            'Всего': gauss_total
        }
    }

#Оценка для n=5
n = 5
ops = estimate_operations(n)

print(f"\nОценка числа арифметических операций для n = {n}:")
print("\nМетод Холецкого:")
print(f"  Разложение A = LL^T: ~{ops['Холецкий']['Разложение']:.0f} операций")
print(f"  Решение двух треугольных систем: ~{ops['Холецкий']['Решение']:.0f} операций")
print(f"  ВСЕГО: ~{ops['Холецкий']['Всего']:.0f} операций")

print("\nМетод Гаусса (LU-разложение):")
print(f"  LU-разложение: ~{ops['Гаусс']['Разложение']:.0f} операций")
print(f"  Решение двух треугольных систем: ~{ops['Гаусс']['Решение']:.0f} операций")
print(f"  ВСЕГО: ~{ops['Гаусс']['Всего']:.0f} операций")

# Сравнение
ratio = ops['Гаусс']['Всего'] / ops['Холецкий']['Всего']
print(f"\nСРАВНЕНИЕ:")
print(f"Метод Холецкого требует примерно в {ratio:.2f} раз меньше операций")
print(f"чем метод Гаусса для матриц размера n×n")

# Сравнение для больших n
print("\nСравнение для разных размеров матриц:")
print("n\tХолецкий\tГаусс\t\tОтношение (Гаусс/Холецкий)")
print("-" * 55)

for n_test in [5, 10, 50, 100]:
    ops_test = estimate_operations(n_test)
    chol_total = ops_test['Холецкий']['Всего']
    gauss_total = ops_test['Гаусс']['Всего']
    ratio_test = gauss_total / chol_total
    print(f"{n_test}\t{chol_total:.0f}\t\t{gauss_total:.0f}\t\t{ratio_test:.2f}")

print("\n" + "="*60)
print("ВЫВОДЫ ПО СРАВНЕНИЮ:")
print("="*60)
print("1. Метод Холецкого требует примерно ВДВОЕ МЕНЬШЕ операций,")
print("   чем метод Гаусса, для больших n.")
print("2. Экономия достигается за счёт использования симметрии матрицы.")
print("3. Однако метод Холецкого применим только для")
print("   СИММЕТРИЧНЫХ ПОЛОЖИТЕЛЬНО ОПРЕДЕЛЁННЫХ матриц.")
print("4. Для матриц общего вида метод Гаусса более универсален.")


4. ОЦЕНКА ЧИСЛА ОПЕРАЦИЙ И СРАВНЕНИЕ С ДРУГИМИ МЕТОДАМИ

Оценка числа арифметических операций для n = 5:

Метод Холецкого:
  Разложение A = LL^T: ~35 операций
  Решение двух треугольных систем: ~50 операций
  ВСЕГО: ~85 операций

Метод Гаусса (LU-разложение):
  LU-разложение: ~70 операций
  Решение двух треугольных систем: ~50 операций
  ВСЕГО: ~120 операций

СРАВНЕНИЕ:
Метод Холецкого требует примерно в 1.41 раз меньше операций
чем метод Гаусса для матриц размера n×n

Сравнение для разных размеров матриц:
n	Холецкий	Гаусс		Отношение (Гаусс/Холецкий)
-------------------------------------------------------
5	85		120		1.41
10	420		815		1.94
50	27100		87075		3.21
100	191700		681650		3.56

ВЫВОДЫ ПО СРАВНЕНИЮ:
1. Метод Холецкого требует примерно ВДВОЕ МЕНЬШЕ операций,
   чем метод Гаусса, для больших n.
2. Экономия достигается за счёт использования симметрии матрицы.
3. Однако метод Холецкого применим только для
   СИММЕТРИЧНЫХ ПОЛОЖИТЕЛЬНО ОПРЕДЕЛЁННЫХ матриц.
4. Для матриц общего вида м

In [8]:
print("\n" + "="*60)
print("5. ПРОВЕРКА РЕШЕНИЯ МЕТОДОМ ГАУССА (numpy.linalg.solve)")
print("="*60)

# Решаем применимую систему методом Гаусса
x_gauss = np.linalg.solve(A_good, b_good)
print(f"Решение методом Гаусса (для проверки):")
print(x_gauss)

# Сравнение с решением Холецкого
if 'x_solution' in locals():
    diff = np.linalg.norm(x_solution - x_gauss)
    print(f"\nРазница между решениями (Холецкий vs Гаусс): {diff:.2e}")
    print("Решения совпадают с высокой точностью.")


5. ПРОВЕРКА РЕШЕНИЯ МЕТОДОМ ГАУССА (numpy.linalg.solve)
Решение методом Гаусса (для проверки):
[0.11676352 0.23200409 0.32650192 0.41918561 0.53853742]

Разница между решениями (Холецкий vs Гаусс): 7.85e-17
Решения совпадают с высокой точностью.
